spring:
  application:
    name: carrinho-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carrinho?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas:
    - carrinho
    user: root
    password: root
