spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sronlemos/papelaria
          default-label: main
          search-paths:
          - 'estoque-config-server/estoque-api*'
server:
  port: 8888
  